export interface BirdStatusInfo {
  code: string;
  description: string;
}

export interface BirdStatusGroup {
  id: string;
  label: string;
  description: string;
}

export const BIRD_STATUS_GROUPS: BirdStatusGroup[] = [
  {
    id: "200",
    label: "Transported Birds (200s)",
    description: "Transported to different location, requires special permit",
  },
  {
    id: "300",
    label: "Normal Wild Birds (300s)",
    description: "Healthy wild birds released in same location",
  },
  {
    id: "400",
    label: "Hand-reared Birds (400s)",
    description: "Raised in captivity or taken as nestling",
  },
  {
    id: "500",
    label: "Sick/Injured Birds (500s)",
    description: "Sick, exhausted, injured, crippled, or deformed",
  },
  {
    id: "700",
    label: "Rehabilitated Birds (700s)",
    description: "Rehabilitated and held longer than 24 hours",
  },
  {
    id: "800",
    label: "Experimental/Falconry (800s)",
    description: "Held for experimental purposes or falconry",
  },
];

// Get all codes for a specific group (e.g., all codes starting with "2" for group "200")
export function getCodesForGroup(groupId: string): string[] {
  const prefix = groupId.charAt(0);
  return Object.keys(BIRD_STATUS_CODES)
    .filter((code) => code.startsWith(prefix))
    .sort();
}

export const BIRD_STATUS_CODES: Record<string, BirdStatusInfo> = {
  // Transported birds (200s)
  "200": { code: "200", description: "Transported with federal band only" },
  "201": { code: "201", description: "Transported with colored leg bands" },
  "202": { code: "202", description: "Transported with neck collar" },
  "206": { code: "206", description: "Transported with misc. metal band and federal band" },
  "207": { code: "207", description: "Transported with double federal bands" },
  "208": { code: "208", description: "Transported with temporary markers" },
  "209": { code: "209", description: "Transported with clipped flight feathers" },
  "210": { code: "210", description: "Transported with clipped feathers and auxiliary markers" },
  "211": { code: "211", description: "Transported and sexed by laparotomy" },
  "212": { code: "212", description: "Transported, sexed by laparotomy with auxiliary markers" },
  "218": { code: "218", description: "Transported with blood sample taken" },
  "219": { code: "219", description: "Transported with blood sample and auxiliary markers" },
  "220": { code: "220", description: "Transported and fostered into wild nest" },
  "221": { code: "221", description: "Transported, fostered with auxiliary markers" },
  "225": { code: "225", description: "Transported with multiple auxiliary markers" },
  "229": { code: "229", description: "Transported with misc. band, federal band, and auxiliary markers" },
  "230": { code: "230", description: "Transported with double federal bands and auxiliary markers" },
  "233": { code: "233", description: "Transported from artificial nest structure" },
  "234": { code: "234", description: "Transported from artificial nest with auxiliary markers" },
  "239": { code: "239", description: "Transported with wing or body tags" },
  "251": { code: "251", description: "Transported with nasal saddle or bill marker" },
  "259": { code: "259", description: "Transported with web tag" },
  "269": { code: "269", description: "Transported with leg flag or streamer" },
  "270": { code: "270", description: "Transported, captured by spotlighting" },
  "271": { code: "271", description: "Transported, captured by spotlighting with auxiliary markers" },
  "285": { code: "285", description: "Transported, miscellaneous combination" },
  "287": { code: "287", description: "Transported, captured with drugs or tranquilizers" },
  "288": { code: "288", description: "Transported, captured with drugs and auxiliary markers" },
  "289": { code: "289", description: "Transported with radio transmitter" },

  // Normal wild birds (300s)
  "300": { code: "300", description: "Normal wild bird with federal band only" },
  "301": { code: "301", description: "Normal wild bird with colored leg bands" },
  "302": { code: "302", description: "Normal wild bird with neck collar" },
  "303": { code: "303", description: "Normal wild bird with reward band" },
  "304": { code: "304", description: "Normal wild bird with control band" },
  "306": { code: "306", description: "Normal wild bird with misc. metal band and federal band" },
  "307": { code: "307", description: "Normal wild bird with double federal bands" },
  "308": { code: "308", description: "Normal wild bird with temporary markers" },
  "309": { code: "309", description: "Normal wild bird with clipped flight feathers" },
  "310": { code: "310", description: "Normal wild bird with clipped feathers and auxiliary markers" },
  "311": { code: "311", description: "Normal wild bird sexed by laparotomy" },
  "312": { code: "312", description: "Normal wild bird sexed by laparotomy with auxiliary markers" },
  "318": { code: "318", description: "Normal wild bird with blood sample taken" },
  "319": { code: "319", description: "Normal wild bird with blood sample and auxiliary markers" },
  "320": { code: "320", description: "Normal wild bird fostered into wild nest" },
  "321": { code: "321", description: "Normal wild bird fostered with auxiliary markers" },
  "325": { code: "325", description: "Normal wild bird with multiple auxiliary markers" },
  "329": { code: "329", description: "Normal wild bird with misc. band, federal band, and auxiliary markers" },
  "330": { code: "330", description: "Normal wild bird with double federal bands and auxiliary markers" },
  "333": { code: "333", description: "Normal wild bird from artificial nest structure" },
  "334": { code: "334", description: "Normal wild bird from artificial nest with auxiliary markers" },
  "339": { code: "339", description: "Normal wild bird with wing or body tags" },
  "351": { code: "351", description: "Normal wild bird with nasal saddle or bill marker" },
  "359": { code: "359", description: "Normal wild bird with web tag" },
  "369": { code: "369", description: "Normal wild bird with leg flag or streamer" },
  "370": { code: "370", description: "Normal wild bird captured by spotlighting" },
  "371": { code: "371", description: "Normal wild bird captured by spotlighting with auxiliary markers" },
  "381": { code: "381", description: "Normal wild bird with radio transmitter" },
  "385": { code: "385", description: "Normal wild bird, miscellaneous combination" },
  "387": { code: "387", description: "Normal wild bird captured with drugs or tranquilizers" },
  "388": { code: "388", description: "Normal wild bird captured with drugs and auxiliary markers" },
  "389": { code: "389", description: "Normal wild bird with radio transmitter" },

  // Hand-reared or game farm birds (400s)
  "400": { code: "400", description: "Hand-reared with federal band only" },
  "401": { code: "401", description: "Hand-reared with colored leg bands" },
  "402": { code: "402", description: "Hand-reared with neck collar" },
  "406": { code: "406", description: "Hand-reared with misc. metal band and federal band" },
  "407": { code: "407", description: "Hand-reared with double federal bands" },
  "408": { code: "408", description: "Hand-reared with temporary markers" },
  "409": { code: "409", description: "Hand-reared with clipped flight feathers" },
  "410": { code: "410", description: "Hand-reared with clipped feathers and auxiliary markers" },
  "411": { code: "411", description: "Hand-reared and sexed by laparotomy" },
  "412": { code: "412", description: "Hand-reared, sexed by laparotomy with auxiliary markers" },
  "418": { code: "418", description: "Hand-reared with blood sample taken" },
  "419": { code: "419", description: "Hand-reared with blood sample and auxiliary markers" },
  "420": { code: "420", description: "Hand-reared and fostered into wild nest" },
  "421": { code: "421", description: "Hand-reared, fostered with auxiliary markers" },
  "425": { code: "425", description: "Hand-reared with multiple auxiliary markers" },
  "429": { code: "429", description: "Hand-reared with misc. band, federal band, and auxiliary markers" },
  "430": { code: "430", description: "Hand-reared with double federal bands and auxiliary markers" },
  "433": { code: "433", description: "Hand-reared from artificial nest structure" },
  "434": { code: "434", description: "Hand-reared from artificial nest with auxiliary markers" },
  "439": { code: "439", description: "Hand-reared with wing or body tags" },
  "440": { code: "440", description: "Hand-reared and oiled" },
  "441": { code: "441", description: "Hand-reared, oiled with auxiliary markers" },
  "451": { code: "451", description: "Hand-reared with nasal saddle or bill marker" },
  "459": { code: "459", description: "Hand-reared with web tag" },
  "469": { code: "469", description: "Hand-reared with leg flag or streamer" },
  "485": { code: "485", description: "Hand-reared, miscellaneous combination" },
  "489": { code: "489", description: "Hand-reared with radio transmitter" },

  // Sick, Exhausted, Injured, Crippled, or Deformed birds (500s)
  "500": { code: "500", description: "Sick/injured with federal band only" },
  "501": { code: "501", description: "Sick/injured with colored leg bands" },
  "502": { code: "502", description: "Sick/injured with neck collar" },
  "506": { code: "506", description: "Sick/injured with misc. metal band and federal band" },
  "507": { code: "507", description: "Sick/injured with double federal bands" },
  "508": { code: "508", description: "Sick/injured with temporary markers" },
  "511": { code: "511", description: "Sick/injured and sexed by laparotomy" },
  "512": { code: "512", description: "Sick/injured, sexed by laparotomy with auxiliary markers" },
  "518": { code: "518", description: "Sick/injured with blood sample taken" },
  "519": { code: "519", description: "Sick/injured with blood sample and auxiliary markers" },
  "520": { code: "520", description: "Sick/injured and fostered into wild nest" },
  "521": { code: "521", description: "Sick/injured, fostered with auxiliary markers" },
  "525": { code: "525", description: "Sick/injured with multiple auxiliary markers" },
  "529": { code: "529", description: "Sick/injured with misc. band, federal band, and auxiliary markers" },
  "530": { code: "530", description: "Sick/injured with double federal bands and auxiliary markers" },
  "533": { code: "533", description: "Sick/injured from artificial nest structure" },
  "534": { code: "534", description: "Sick/injured from artificial nest with auxiliary markers" },
  "539": { code: "539", description: "Sick/injured with wing or body tags" },
  "540": { code: "540", description: "Sick/injured and oiled" },
  "541": { code: "541", description: "Sick/injured, oiled with auxiliary markers" },
  "551": { code: "551", description: "Sick/injured with nasal saddle or bill marker" },
  "559": { code: "559", description: "Sick/injured with web tag" },
  "569": { code: "569", description: "Sick/injured with leg flag or streamer" },
  "570": { code: "570", description: "Sick/injured, captured by spotlighting" },
  "571": { code: "571", description: "Sick/injured, captured by spotlighting with auxiliary markers" },
  "585": { code: "585", description: "Sick/injured, miscellaneous combination" },
  "587": { code: "587", description: "Sick/injured, captured with drugs or tranquilizers" },
  "588": { code: "588", description: "Sick/injured, captured with drugs and auxiliary markers" },
  "589": { code: "589", description: "Sick/injured with radio transmitter" },

  // Rehabilitated and held birds (700s)
  "700": { code: "700", description: "Rehabilitated and held with federal band only" },
  "701": { code: "701", description: "Rehabilitated and held with colored leg bands" },
  "702": { code: "702", description: "Rehabilitated and held with neck collar" },
  "706": { code: "706", description: "Rehabilitated and held with misc. metal band and federal band" },
  "707": { code: "707", description: "Rehabilitated and held with double federal bands" },
  "708": { code: "708", description: "Rehabilitated and held with temporary markers" },
  "711": { code: "711", description: "Rehabilitated and held, sexed by laparotomy" },
  "712": { code: "712", description: "Rehabilitated and held, sexed by laparotomy with auxiliary markers" },
  "720": { code: "720", description: "Rehabilitated and held, fostered into wild nest" },
  "721": { code: "721", description: "Rehabilitated and held, fostered with auxiliary markers" },
  "725": { code: "725", description: "Rehabilitated and held with multiple auxiliary markers" },
  "729": { code: "729", description: "Rehabilitated and held with misc. band, federal band, and auxiliary markers" },
  "730": { code: "730", description: "Rehabilitated and held with double federal bands and auxiliary markers" },
  "739": { code: "739", description: "Rehabilitated and held with wing or body tags" },
  "740": { code: "740", description: "Rehabilitated and held, oiled" },
  "741": { code: "741", description: "Rehabilitated and held, oiled with auxiliary markers" },
  "751": { code: "751", description: "Rehabilitated and held with nasal saddle or bill marker" },
  "759": { code: "759", description: "Rehabilitated and held with web tag" },
  "769": { code: "769", description: "Rehabilitated and held with leg flag or streamer" },
  "785": { code: "785", description: "Rehabilitated and held, miscellaneous combination" },
  "787": { code: "787", description: "Rehabilitated and held, captured with drugs or tranquilizers" },
  "788": { code: "788", description: "Rehabilitated and held, captured with drugs and auxiliary markers" },
  "789": { code: "789", description: "Rehabilitated and held with radio transmitter" },

  // Held for experimental or other purposes (800s)
  "800": { code: "800", description: "Held for experimental purposes with federal band only" },
  "801": { code: "801", description: "Held for experimental purposes with colored leg bands" },
  "802": { code: "802", description: "Held for experimental purposes with neck collar" },
  "806": { code: "806", description: "Held for experimental purposes with misc. metal band and federal band" },
  "807": { code: "807", description: "Held for experimental purposes with double federal bands" },
  "808": { code: "808", description: "Held for experimental purposes with temporary markers" },
  "809": { code: "809", description: "Held for experimental purposes with clipped flight feathers" },
  "810": { code: "810", description: "Held for experimental purposes with clipped feathers and auxiliary markers" },
  "811": { code: "811", description: "Held for experimental purposes, sexed by laparotomy" },
  "812": { code: "812", description: "Held for experimental purposes, sexed by laparotomy with auxiliary markers" },
  "818": { code: "818", description: "Held for experimental purposes with blood sample taken" },
  "819": { code: "819", description: "Held for experimental purposes with blood sample and auxiliary markers" },
  "820": { code: "820", description: "Held for experimental purposes, fostered into wild nest" },
  "821": { code: "821", description: "Held for experimental purposes, fostered with auxiliary markers" },
  "825": { code: "825", description: "Held for experimental purposes with multiple auxiliary markers" },
  "829": { code: "829", description: "Held for experimental purposes with misc. band, federal band, and auxiliary markers" },
  "830": { code: "830", description: "Held for experimental purposes with double federal bands and auxiliary markers" },
  "833": { code: "833", description: "Held for experimental purposes from artificial nest structure" },
  "834": { code: "834", description: "Held for experimental purposes from artificial nest with auxiliary markers" },
  "839": { code: "839", description: "Held for experimental purposes with wing or body tags" },
  "851": { code: "851", description: "Held for experimental purposes with nasal saddle or bill marker" },
  "859": { code: "859", description: "Held for experimental purposes with web tag" },
  "869": { code: "869", description: "Held for experimental purposes with leg flag or streamer" },
  "870": { code: "870", description: "Held for experimental purposes, captured by spotlighting" },
  "871": { code: "871", description: "Held for experimental purposes, captured by spotlighting with auxiliary markers" },
  "885": { code: "885", description: "Held for experimental purposes, miscellaneous combination" },
  "887": { code: "887", description: "Held for experimental purposes, captured with drugs or tranquilizers" },
  "888": { code: "888", description: "Held for experimental purposes, captured with drugs and auxiliary markers" },
  "889": { code: "889", description: "Held for experimental purposes with radio transmitter" },
};

export const DEFAULT_BIRD_STATUS = "300";

export function getBirdStatusDescription(code: string): string {
  return BIRD_STATUS_CODES[code]?.description || code;
}
