export interface Species {
  code: string; // Species code (e.g., "ABDU", "AMGO")
  pseudoSpeciesType: string; // Type (e.g., "Species", "Hybrid")
  speciesDescriptionMBO: string; // MBO description
  speciesDescriptionCMMN: string; // CMMN description
  speciesFrench: string; // French name
  speciesScientific: string; // Scientific name
}

export const SPECIES_MAP: Record<string, Species> = {
  ABDU: {
    code: "ABDU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Black Duck",
    speciesDescriptionCMMN: "American Black Duck",
    speciesFrench: "Canard noir",
    speciesScientific: "Anas rubripes",
  },
  AGWT: {
    code: "AGWT",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "(American) Green-winged Teal",
    speciesDescriptionCMMN: "Green-winged (American) Teal",
    speciesFrench: "Sarcelle d'hiver",
    speciesScientific: "Anas crecca carolinensis",
  },
  ALFL: {
    code: "ALFL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Alder Flycatcher",
    speciesDescriptionCMMN: "Alder Flycatcher",
    speciesFrench: "Moucherolle des aulnes",
    speciesScientific: "Empidonax alnorum",
  },
  AMBI: {
    code: "AMBI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Bittern",
    speciesDescriptionCMMN: "American Bittern",
    speciesFrench: "Butor d'Amérique",
    speciesScientific: "Botaurus lentiginosus",
  },
  AMCR: {
    code: "AMCR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Crow",
    speciesDescriptionCMMN: "American Crow",
    speciesFrench: "Corneille d'Amérique",
    speciesScientific: "Corvus brachyrhynchos",
  },
  AMGO: {
    code: "AMGO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Goldfinch",
    speciesDescriptionCMMN: "American Goldfinch",
    speciesFrench: "Chardonneret jaune",
    speciesScientific: "Spinus tristis",
  },
  AMKE: {
    code: "AMKE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Kestrel",
    speciesDescriptionCMMN: "American Kestrel",
    speciesFrench: "Crécerelle d'Amérique",
    speciesScientific: "Falco sparverius",
  },
  AMPI: {
    code: "AMPI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Pipit",
    speciesDescriptionCMMN: "American Pipit",
    speciesFrench: "Pipit d'Amérique",
    speciesScientific: "Anthus rubescens",
  },
  AMRE: {
    code: "AMRE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Redstart",
    speciesDescriptionCMMN: "American Redstart",
    speciesFrench: "Paruline flamboyante",
    speciesScientific: "Setophaga ruticilla",
  },
  AMRO: {
    code: "AMRO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Robin",
    speciesDescriptionCMMN: "American Robin",
    speciesFrench: "Merle d'Amérique",
    speciesScientific: "Turdus migratorius",
  },
  AMWI: {
    code: "AMWI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Wigeon",
    speciesDescriptionCMMN: "American Wigeon",
    speciesFrench: "Canard d'Amérique",
    speciesScientific: "Mareca americana",
  },
  AMWO: {
    code: "AMWO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Woodcock",
    speciesDescriptionCMMN: "American Woodcock",
    speciesFrench: "Bécasse d'Amérique",
    speciesScientific: "Scolopax minor",
  },
  ATBR: {
    code: "ATBR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Atlantic Brant",
    speciesDescriptionCMMN: "Atlantic Brant",
    speciesFrench: "Bernache cravant",
    speciesScientific: "Branta bernicla",
  },
  ATSP: {
    code: "ATSP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "American Tree Sparrow",
    speciesDescriptionCMMN: "American Tree Sparrow",
    speciesFrench: "Bruant hudsonien",
    speciesScientific: "Spizelloides arborea",
  },
  BAEA: {
    code: "BAEA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Bald Eagle",
    speciesDescriptionCMMN: "Bald Eagle",
    speciesFrench: "Pygargue à tête blanche",
    speciesScientific: "Haliaeetus leucocephalus",
  },
  BANS: {
    code: "BANS",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Bank Swallow",
    speciesDescriptionCMMN: "Bank Swallow",
    speciesFrench: "Hirondelle de rivage",
    speciesScientific: "Riparia riparia",
  },
  BAOR: {
    code: "BAOR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Baltimore Oriole",
    speciesDescriptionCMMN: "Baltimore Oriole",
    speciesFrench: "Oriole de Baltimore",
    speciesScientific: "Icterus galbula",
  },
  BARS: {
    code: "BARS",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Barn Swallow",
    speciesDescriptionCMMN: "Barn Swallow",
    speciesFrench: "Hirondelle rustique",
    speciesScientific: "Hirundo rustica",
  },
  BAWW: {
    code: "BAWW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black-and-white Warbler",
    speciesDescriptionCMMN: "Black-and-white Warbler",
    speciesFrench: "Paruline noir et blanc",
    speciesScientific: "Mniotilta varia",
  },
  BBCU: {
    code: "BBCU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black-billed Cuckoo",
    speciesDescriptionCMMN: "Black-billed Cuckoo",
    speciesFrench: "Coulicou à bec noir",
    speciesScientific: "Coccyzus erythropthalmus",
  },
  BBPL: {
    code: "BBPL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black-bellied Plover",
    speciesDescriptionCMMN: "Black-bellied Plover",
    speciesFrench: "Pluvier argenté",
    speciesScientific: "Pluvialis squatarola",
  },
  BBWA: {
    code: "BBWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Bay-breasted Warbler",
    speciesDescriptionCMMN: "Bay-breasted Warbler",
    speciesFrench: "Paruline à poitrine baie",
    speciesScientific: "Setophaga castanea",
  },
  BBWO: {
    code: "BBWO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black-backed Woodpecker",
    speciesDescriptionCMMN: "Black-backer Woodpecker",
    speciesFrench: "Pic à dos noir",
    speciesScientific: "Picoides arcticus",
  },
  BCCH: {
    code: "BCCH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black-capped Chickadee",
    speciesDescriptionCMMN: "Black-capped Chickadee",
    speciesFrench: "Mésange à tête noire",
    speciesScientific: "Poecile atricapillus",
  },
  BCNH: {
    code: "BCNH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black-crowned Night-Heron",
    speciesDescriptionCMMN: "Black-crowned Night-Heron",
    speciesFrench: "Bihoreau gris",
    speciesScientific: "Nycticorax nycticorax",
  },
  BDOW: {
    code: "BDOW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Barred Owl",
    speciesDescriptionCMMN: "Barred Owl",
    speciesFrench: "Chouette rayée",
    speciesScientific: "Strix varia",
  },
  BEKI: {
    code: "BEKI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Belted Kingfisher",
    speciesDescriptionCMMN: "Belted Kingfisher",
    speciesFrench: "Martin-pêcheur d'Amérique",
    speciesScientific: "Megaceryle alcyon",
  },
  BGGN: {
    code: "BGGN",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Blue-gray Gnatcatcher",
    speciesDescriptionCMMN: "Blue-gray Gnatcatcher",
    speciesFrench: "Gobemoucheron gris-bleu",
    speciesScientific: "Polioptila caerulea",
  },
  BHCO: {
    code: "BHCO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Brown-headed Cowbird",
    speciesDescriptionCMMN: "Brown-headed Cowbird",
    speciesFrench: "Vacher à tête brune",
    speciesScientific: "Molothrus ater",
  },
  BHVI: {
    code: "BHVI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Blue-headed Vireo",
    speciesDescriptionCMMN: "Blue-headed Vireo",
    speciesFrench: "Viréo à tête bleue",
    speciesScientific: "Vireo solitarius",
  },
  BITH: {
    code: "BITH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Bicknell's Thrush",
    speciesDescriptionCMMN: "Bicknell's Thrush",
    speciesFrench: "Grive de Bicknell",
    speciesScientific: "Catharus bicknelli",
  },
  BLBW: {
    code: "BLBW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Blackburnian Warbler",
    speciesDescriptionCMMN: "Blackburnian Warbler",
    speciesFrench: "Paruline à gorge orangée",
    speciesScientific: "Setophaga fusca",
  },
  BLJA: {
    code: "BLJA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Blue Jay",
    speciesDescriptionCMMN: "Blue Jay",
    speciesFrench: "Geai bleu",
    speciesScientific: "Cyanocitta cristata",
  },
  BLPW: {
    code: "BLPW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Blackpoll Warbler",
    speciesDescriptionCMMN: "Blackpoll Warbler",
    speciesFrench: "Paruline rayée",
    speciesScientific: "Setophaga striata",
  },
  BLSC: {
    code: "BLSC",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black Scoter",
    speciesDescriptionCMMN: "Black Scoter",
    speciesFrench: "Macreuse à bec jaune",
    speciesScientific: "Melanitta americana",
  },
  BLTE: {
    code: "BLTE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black Tern",
    speciesDescriptionCMMN: "Black Tern",
    speciesFrench: "Guifette noire",
    speciesScientific: "Chlidonias niger",
  },
  BOBO: {
    code: "BOBO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Bobolink",
    speciesDescriptionCMMN: "Bobolink",
    speciesFrench: "Goglu des prés",
    speciesScientific: "Dolichonyx oryzivorus",
  },
  BOCH: {
    code: "BOCH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Boreal Chickadee",
    speciesDescriptionCMMN: "Boreal Chickadee",
    speciesFrench: "Mésange à tête brune",
    speciesScientific: "Poecile hudsonicus",
  },
  BOOW: {
    code: "BOOW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Boreal Owl",
    speciesDescriptionCMMN: "Boreal Owl",
    speciesFrench: "Nyctale de Tengmalm",
    speciesScientific: "Aegolius funereus",
  },
  BOWA: {
    code: "BOWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Bohemian Waxwing",
    speciesDescriptionCMMN: "Bohemian Waxwing",
    speciesFrench: "Jaseur boréal",
    speciesScientific: "Bombycilla garrulus",
  },
  BRCR: {
    code: "BRCR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Brown Creeper",
    speciesDescriptionCMMN: "Brown Creeper",
    speciesFrench: "Grimpereau brun",
    speciesScientific: "Certhia americana",
  },
  BRTH: {
    code: "BRTH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Brown Thrasher",
    speciesDescriptionCMMN: "Brown Thrasher",
    speciesFrench: "Moqueur roux",
    speciesScientific: "Toxostoma rufum",
  },
  BRWA: {
    code: "BRWA",
    pseudoSpeciesType: "Hybrid",
    speciesDescriptionMBO: "Brewster's Warbler",
    speciesDescriptionCMMN: "Brewster's Warbler",
    speciesFrench: "Paruline de Brewster",
    speciesScientific: "",
  },
  BTBW: {
    code: "BTBW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black-throated Blue Warbler",
    speciesDescriptionCMMN: "Black-throated Blue Warbler",
    speciesFrench: "Paruline bleue",
    speciesScientific: "Setophaga caerulescens",
  },
  BTNW: {
    code: "BTNW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Black-throated Green Warbler",
    speciesDescriptionCMMN: "Black-throated Green Warbler",
    speciesFrench: "Paruline à gorge noire",
    speciesScientific: "Setophaga virens",
  },
  BUFF: {
    code: "BUFF",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Bufflehead",
    speciesDescriptionCMMN: "Bufflehead",
    speciesFrench: "Petit Garrot",
    speciesScientific: "Bucephala albeola",
  },
  BWHA: {
    code: "BWHA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Broad-winged Hawk",
    speciesDescriptionCMMN: "Broad-winged Hawk",
    speciesFrench: "Petite Buse",
    speciesScientific: "Buteo platypterus",
  },
  BWTE: {
    code: "BWTE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Blue-winged Teal",
    speciesDescriptionCMMN: "Blue-winged Teal",
    speciesFrench: "Sarcelle à ailes bleues",
    speciesScientific: "Spatula discors",
  },
  BWWA: {
    code: "BWWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Blue-winged Warbler",
    speciesDescriptionCMMN: "Blue-winged Warbler",
    speciesFrench: "Paruline à ailes bleues",
    speciesScientific: "Vermivora cyanoptera",
  },
  CACG: {
    code: "CACG",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Cackling Goose",
    speciesDescriptionCMMN: "Cackling Goose",
    speciesFrench: "Bernache de Hutchins",
    speciesScientific: "Branta hutchinsii",
  },
  CANG: {
    code: "CANG",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Canada Goose",
    speciesDescriptionCMMN: "Canada Goose",
    speciesFrench: "Bernache du Canada",
    speciesScientific: "Branta canadensis",
  },
  CARW: {
    code: "CARW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Carolina Wren",
    speciesDescriptionCMMN: "Carolina Wren",
    speciesFrench: "Troglodyte de Caroline",
    speciesScientific: "Thryothorus ludovicianus",
  },
  CATE: {
    code: "CATE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Caspian Tern",
    speciesDescriptionCMMN: "Caspian Tern",
    speciesFrench: "Sterne caspienne",
    speciesScientific: "Hydroprogne caspia",
  },
  CAWA: {
    code: "CAWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Canada Warbler",
    speciesDescriptionCMMN: "Canada Warbler",
    speciesFrench: "Paruline du Canada",
    speciesScientific: "Cardellina canadensis",
  },
  CCSP: {
    code: "CCSP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Clay-colored Sparrow",
    speciesDescriptionCMMN: "Clay-colored Sparrow",
    speciesFrench: "Bruant des plaines",
    speciesScientific: "Spizella pallida",
  },
  CEDW: {
    code: "CEDW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Cedar Waxwing",
    speciesDescriptionCMMN: "Cedar Waxwing",
    speciesFrench: "Jaseur d'Amérique",
    speciesScientific: "Bombycilla cedrorum",
  },
  CHSP: {
    code: "CHSP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Chipping Sparrow",
    speciesDescriptionCMMN: "Chipping Sparrow",
    speciesFrench: "Bruant familier",
    speciesScientific: "Spizella passerina",
  },
  CHSW: {
    code: "CHSW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Chimney Swift",
    speciesDescriptionCMMN: "Chimney Swift",
    speciesFrench: "Martinet ramoneur",
    speciesScientific: "Chaetura pelagica",
  },
  CLSW: {
    code: "CLSW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Cliff Swallow",
    speciesDescriptionCMMN: "Cliff Swallow",
    speciesFrench: "Hirondelle à front blanc",
    speciesScientific: "Petrochelidon pyrrhonota",
  },
  CMWA: {
    code: "CMWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Cape May Warbler",
    speciesDescriptionCMMN: "Cape May Warbler",
    speciesFrench: "Paruline tigrée",
    speciesScientific: "Setophaga tigrina",
  },
  COGA: {
    code: "COGA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Gallinule",
    speciesDescriptionCMMN: "Common Gallinule",
    speciesFrench: "Gallinule d'Amérique",
    speciesScientific: "Gallinula galeata",
  },
  COGO: {
    code: "COGO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Goldeneye",
    speciesDescriptionCMMN: "Common Goldeneye",
    speciesFrench: "Garrot à oeil d'or",
    speciesScientific: "Bucephala clangula",
  },
  COGR: {
    code: "COGR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Grackle",
    speciesDescriptionCMMN: "Common Grackle",
    speciesFrench: "Quiscale bronzé",
    speciesScientific: "Quiscalus quiscula",
  },
  COHA: {
    code: "COHA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Cooper's Hawk",
    speciesDescriptionCMMN: "Cooper's Hawk",
    speciesFrench: "Épervier de Cooper",
    speciesScientific: "Accipiter cooperii",
  },
  COLO: {
    code: "COLO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Loon",
    speciesDescriptionCMMN: "Common Loon",
    speciesFrench: "Plongeon huard",
    speciesScientific: "Gavia immer",
  },
  COME: {
    code: "COME",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Merganser",
    speciesDescriptionCMMN: "Common Merganser",
    speciesFrench: "Grand Harle",
    speciesScientific: "Mergus merganser",
  },
  CONI: {
    code: "CONI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Nighthawk",
    speciesDescriptionCMMN: "Common Nighthawk",
    speciesFrench: "Engoulevent d'Amérique",
    speciesScientific: "Chordeiles minor",
  },
  CONW: {
    code: "CONW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Connecticut Warbler",
    speciesDescriptionCMMN: "Connecticut Warbler",
    speciesFrench: "Paruline à gorge grise",
    speciesScientific: "Oporornis agilis",
  },
  CORA: {
    code: "CORA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Raven",
    speciesDescriptionCMMN: "Common Raven",
    speciesFrench: "Grand Corbeau",
    speciesScientific: "Corvus corax",
  },
  CORE: {
    code: "CORE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Redpoll",
    speciesDescriptionCMMN: "Common Redpoll",
    speciesFrench: "Sizerin flammé",
    speciesScientific: "Acanthis flammea",
  },
  COTE: {
    code: "COTE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Tern",
    speciesDescriptionCMMN: "Common Tern",
    speciesFrench: "Sterne pierregarin",
    speciesScientific: "Sterna hirundo",
  },
  COYE: {
    code: "COYE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Common Yellowthroat",
    speciesDescriptionCMMN: "Common Yellowthroat",
    speciesFrench: "Paruline masquée",
    speciesScientific: "Geothlypis trichas",
  },
  CSWA: {
    code: "CSWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Chestnut-sided Warbler",
    speciesDescriptionCMMN: "Chestnut-sided Warbler",
    speciesFrench: "Paruline à flancs marron",
    speciesScientific: "Setophaga pensylvanica",
  },
  DCCO: {
    code: "DCCO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Double-crested Cormorant",
    speciesDescriptionCMMN: "Double-crested Cormorant",
    speciesFrench: "Cormoran à aigrettes",
    speciesScientific: "Phalacrocorax auritus",
  },
  DOWO: {
    code: "DOWO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Downy Woodpecker",
    speciesDescriptionCMMN: "Downy Woodpecker",
    speciesFrench: "Pic mineur",
    speciesScientific: "Dryobates pubescens",
  },
  DUNL: {
    code: "DUNL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Dunlin",
    speciesDescriptionCMMN: "Dunlin",
    speciesFrench: "Bécasseau variable",
    speciesScientific: "Calidris alpina",
  },
  EABL: {
    code: "EABL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Eastern Bluebird",
    speciesDescriptionCMMN: "Eastern Bluebird",
    speciesFrench: "Merlebleu de l'Est",
    speciesScientific: "Sialia sialis",
  },
  EAKI: {
    code: "EAKI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Eastern Kingbird",
    speciesDescriptionCMMN: "Eastern Kingbird",
    speciesFrench: "Tyran tritri",
    speciesScientific: "Tyrannus tyrannus",
  },
  EAME: {
    code: "EAME",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Eastern Meadowlark",
    speciesDescriptionCMMN: "Eastern Meadowlark",
    speciesFrench: "Sturnelle des prés",
    speciesScientific: "Sturnella magna",
  },
  EAPH: {
    code: "EAPH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Eastern Phoebe",
    speciesDescriptionCMMN: "Eastern Phoebe",
    speciesFrench: "Moucherolle phébi",
    speciesScientific: "Sayornis phoebe",
  },
  EASO: {
    code: "EASO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Eastern Screech-Owl",
    speciesDescriptionCMMN: "Eastern Screech-Owl",
    speciesFrench: "Petit-duc maculé",
    speciesScientific: "Megascops asio",
  },
  EATO: {
    code: "EATO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Eastern Towhee",
    speciesDescriptionCMMN: "Eastern Towhee",
    speciesFrench: "Tohi à flancs roux",
    speciesScientific: "Pipilo erythrophthalmus",
  },
  EAWP: {
    code: "EAWP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Eastern Wood-Pewee",
    speciesDescriptionCMMN: "Eastern Wood-Pewee",
    speciesFrench: "Pioui de l'Est",
    speciesScientific: "Contopus virens",
  },
  EUST: {
    code: "EUST",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "European Starling",
    speciesDescriptionCMMN: "European Starling",
    speciesFrench: "Étourneau sansonnet",
    speciesScientific: "Sturnus vulgaris",
  },
  EVGR: {
    code: "EVGR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Evening Grosbeak",
    speciesDescriptionCMMN: "Evening Grosbeak",
    speciesFrench: "Gros-bec errant",
    speciesScientific: "Coccothraustes vespertinus",
  },
  EWCS: {
    code: "EWCS",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "(Eastern) White-crowned Sparrow",
    speciesDescriptionCMMN: "White-crowned Sparrow (Eastern)",
    speciesFrench: "Bruant à couronne blanche",
    speciesScientific: "Zonotrichia leucophrys leucophrys",
  },
  EWPW: {
    code: "EWPW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Eastern Whip-poor-will",
    speciesDescriptionCMMN: "Eastern Whip-poor-will",
    speciesFrench: "Engoulevent bois-pourri",
    speciesScientific: "Antrostomus vociferus",
  },
  FICR: {
    code: "FICR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Fish Crow",
    speciesDescriptionCMMN: "Fish Crow",
    speciesFrench: "Corneille de rivage",
    speciesScientific: "Corvus ossifragus",
  },
  FISP: {
    code: "FISP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Field Sparrow",
    speciesDescriptionCMMN: "Field Sparrow",
    speciesFrench: "Bruant des champs",
    speciesScientific: "Spizella pusilla",
  },
  FOSP: {
    code: "FOSP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Fox Sparrow",
    speciesDescriptionCMMN: "Fox Sparrow",
    speciesFrench: "Bruant fauve",
    speciesScientific: "Passerella iliaca",
  },
  GADW: {
    code: "GADW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Gadwall",
    speciesDescriptionCMMN: "Gadwall",
    speciesFrench: "Canard chipeau",
    speciesScientific: "Mareca strepera",
  },
  GBBG: {
    code: "GBBG",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Great Black-backed Gull",
    speciesDescriptionCMMN: "Great Black-backed Gull",
    speciesFrench: "Goéland marin",
    speciesScientific: "Larus marinus",
  },
  GBHE: {
    code: "GBHE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Great Blue Heron",
    speciesDescriptionCMMN: "Great Blue Heron",
    speciesFrench: "Grand Héron",
    speciesScientific: "Ardea herodias",
  },
  GCFL: {
    code: "GCFL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Great Crested Flycatcher",
    speciesDescriptionCMMN: "Great Crested Flycatcher",
    speciesFrench: "Tyran huppé",
    speciesScientific: "Myiarchus crinitus",
  },
  GCKI: {
    code: "GCKI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Golden-crowned Kinglet",
    speciesDescriptionCMMN: "Golden-crowned Kinglet",
    speciesFrench: "Roitelet à couronne dorée",
    speciesScientific: "Regulus satrapa",
  },
  GCTH: {
    code: "GCTH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Gray-cheeked Thrush",
    speciesDescriptionCMMN: "Gray-cheeked Thrush",
    speciesFrench: "Grive à joues grises",
    speciesScientific: "Catharus minimus",
  },
  GGOW: {
    code: "GGOW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Great Gray Owl",
    speciesDescriptionCMMN: "Great Gray Owl",
    speciesFrench: "Chouette lapone",
    speciesScientific: "Strix nebulosa",
  },
  GHOW: {
    code: "GHOW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Great Horned Owl",
    speciesDescriptionCMMN: "Great Horned Owl",
    speciesFrench: "Grand-duc d'Amérique",
    speciesScientific: "Bubo virginianus",
  },
  GOEA: {
    code: "GOEA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Golden Eagle",
    speciesDescriptionCMMN: "Golden Eagle",
    speciesFrench: "Aigle royal",
    speciesScientific: "Aquila chrysaetos",
  },
  GRCA: {
    code: "GRCA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Gray Catbird",
    speciesDescriptionCMMN: "Gray Catbird",
    speciesFrench: "Moqueur chat",
    speciesScientific: "Dumetella carolinensis",
  },
  GREG: {
    code: "GREG",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Great Egret",
    speciesDescriptionCMMN: "Great Egret",
    speciesFrench: "Grande Aigrette",
    speciesScientific: "Ardea alba",
  },
  GRHE: {
    code: "GRHE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Green Heron",
    speciesDescriptionCMMN: "Green Heron",
    speciesFrench: "Héron vert",
    speciesScientific: "Butorides virescens",
  },
  GRSC: {
    code: "GRSC",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Greater Scaup",
    speciesDescriptionCMMN: "Greater Scaup",
    speciesFrench: "Fuligule milouinan",
    speciesScientific: "Aythya marila",
  },
  GRSP: {
    code: "GRSP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Grasshopper Sparrow",
    speciesDescriptionCMMN: "Grasshopper Sparrow",
    speciesFrench: "Bruant sauterelle",
    speciesScientific: "Ammodramus savannarum",
  },
  GRYE: {
    code: "GRYE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Greater Yellowlegs",
    speciesDescriptionCMMN: "Greater Yellowlegs",
    speciesFrench: "Grand Chevalier",
    speciesScientific: "Tringa melanoleuca",
  },
  GSGO: {
    code: "GSGO",
    pseudoSpeciesType: "Subspecies",
    speciesDescriptionMBO: "Greater Snow Goose",
    speciesDescriptionCMMN: "Greater Snow Goose",
    speciesFrench: "Grande Oie des neiges",
    speciesScientific: "Anser caerulescens atlanticus",
  },
  GWFG: {
    code: "GWFG",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Greater White-fronted Goose",
    speciesDescriptionCMMN: "Greater White-fronted Goose",
    speciesFrench: "Oie rieuse",
    speciesScientific: "Anser albifrons",
  },
  GWWA: {
    code: "GWWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Golden-winged Warbler",
    speciesDescriptionCMMN: "Golden-winged Warbler",
    speciesFrench: "Paruline à ailes dorées",
    speciesScientific: "Vermivora chrysoptera",
  },
  HAWO: {
    code: "HAWO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Hairy Woodpecker",
    speciesDescriptionCMMN: "Hairy Woodpecker",
    speciesFrench: "Pic chevelu",
    speciesScientific: "Dryobates villosus",
  },
  HERG: {
    code: "HERG",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Herring Gull",
    speciesDescriptionCMMN: "Herring Gull",
    speciesFrench: "Goéland argenté",
    speciesScientific: "Larus argentatus",
  },
  HETH: {
    code: "HETH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Hermit Thrush",
    speciesDescriptionCMMN: "Hermit Thrush",
    speciesFrench: "Grive solitaire",
    speciesScientific: "Catharus guttatus",
  },
  HOFI: {
    code: "HOFI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "House Finch",
    speciesDescriptionCMMN: "House Finch",
    speciesFrench: "Roselin familier",
    speciesScientific: "Haemorhous mexicanus",
  },
  HOLA: {
    code: "HOLA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Horned Lark",
    speciesDescriptionCMMN: "Horned Lark",
    speciesFrench: "Alouette hausse-col",
    speciesScientific: "Eremophila alpestris",
  },
  HOME: {
    code: "HOME",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Hooded Merganser",
    speciesDescriptionCMMN: "Hooded Merganser",
    speciesFrench: "Harle couronné",
    speciesScientific: "Lophodytes cucullatus",
  },
  HORE: {
    code: "HORE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Hoary Redpoll",
    speciesDescriptionCMMN: "Hoary Redpoll",
    speciesFrench: "Sizerin blanchâtre",
    speciesScientific: "Acanthis hornemanni",
  },
  HOSP: {
    code: "HOSP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "House Sparrow",
    speciesDescriptionCMMN: "House Sparrow",
    speciesFrench: "Moineau domestique",
    speciesScientific: "Passer domesticus",
  },
  HOWA: {
    code: "HOWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Hooded Warbler",
    speciesDescriptionCMMN: "Hooded Warbler",
    speciesFrench: "Paruline à capuchon",
    speciesScientific: "Setophaga citrina",
  },
  HOWR: {
    code: "HOWR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "House Wren",
    speciesDescriptionCMMN: "House Wren",
    speciesFrench: "Troglodyte familier",
    speciesScientific: "Troglodytes aedon",
  },
  HYWA: {
    code: "HYWA",
    pseudoSpeciesType: "Hybrid",
    speciesDescriptionMBO: "Hybrid Warbler",
    speciesDescriptionCMMN: "",
    speciesFrench: "Paruline hybride",
    speciesScientific: "Hybrid Warbler",
  },
  ICGU: {
    code: "ICGU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Iceland Gull",
    speciesDescriptionCMMN: "Iceland Gull",
    speciesFrench: "Goéland arctique",
    speciesScientific: "Larus glaucoides",
  },
  INBU: {
    code: "INBU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Indigo Bunting",
    speciesDescriptionCMMN: "Indigo Bunting",
    speciesFrench: "Passerin indigo",
    speciesScientific: "Passerina cyanea",
  },
  KILL: {
    code: "KILL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Killdeer",
    speciesDescriptionCMMN: "Killdeer",
    speciesFrench: "Pluvier kildir",
    speciesScientific: "Charadrius vociferus",
  },
  LALO: {
    code: "LALO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Lapland Longspur",
    speciesDescriptionCMMN: "",
    speciesFrench: "Plectrophane lapon",
    speciesScientific: "Calcarius lapponicus",
  },
  LAWA: {
    code: "LAWA",
    pseudoSpeciesType: "Hybrid",
    speciesDescriptionMBO: "Lawrence's Warbler",
    speciesDescriptionCMMN: "Lawrence's Warbler",
    speciesFrench: "Paruline de Lawrence",
    speciesScientific: "",
  },
  LEBI: {
    code: "LEBI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Least Bittern",
    speciesDescriptionCMMN: "Least Bittern",
    speciesFrench: "Petit Blongios",
    speciesScientific: "",
  },
  LEFL: {
    code: "LEFL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Least Flycatcher",
    speciesDescriptionCMMN: "Least Flycatcher",
    speciesFrench: "Moucherolle tchébec",
    speciesScientific: "Empidonax minimus",
  },
  LEOW: {
    code: "LEOW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Long-eared Owl",
    speciesDescriptionCMMN: "Long-eared Owl",
    speciesFrench: "Hibou moyen-duc",
    speciesScientific: "Asio otus",
  },
  LESA: {
    code: "LESA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Least Sandpiper",
    speciesDescriptionCMMN: "Least Sandpiper",
    speciesFrench: "Bécasseau minuscule",
    speciesScientific: "Calidris minutilla",
  },
  LESC: {
    code: "LESC",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Lesser Scaup",
    speciesDescriptionCMMN: "Lesser Scaup",
    speciesFrench: "Petit Fuligule",
    speciesScientific: "Aythya affinis",
  },
  LEYE: {
    code: "LEYE",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Lesser Yellowlegs",
    speciesDescriptionCMMN: "Lesser Yellowlegs",
    speciesFrench: "Petit Chevalier",
    speciesScientific: "Tringa flavipes",
  },
  LISP: {
    code: "LISP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Lincoln's Sparrow",
    speciesDescriptionCMMN: "Lincoln's Sparrow",
    speciesFrench: "Bruant de Lincoln",
    speciesScientific: "Melospiza lincolnii",
  },
  LSGO: {
    code: "LSGO",
    pseudoSpeciesType: "Subspecies",
    speciesDescriptionMBO: "Lesser Snow Goose",
    speciesDescriptionCMMN: "Lesser Snow Goose",
    speciesFrench: "Petite Oie des neiges",
    speciesScientific: "Anser caerulescens caerulescens",
  },
  MALL: {
    code: "MALL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Mallard",
    speciesDescriptionCMMN: "Mallard",
    speciesFrench: "Canard colvert",
    speciesScientific: "Anas platyrhynchos",
  },
  MAWA: {
    code: "MAWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Magnolia Warbler",
    speciesDescriptionCMMN: "Magnolia Warbler",
    speciesFrench: "Paruline à tête cendrée",
    speciesScientific: "Setophaga magnolia",
  },
  MAWR: {
    code: "MAWR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Marsh Wren",
    speciesDescriptionCMMN: "Marsh Wren",
    speciesFrench: "Troglodyte des marais",
    speciesScientific: "Cistothorus palustris",
  },
  MERL: {
    code: "MERL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Merlin",
    speciesDescriptionCMMN: "Merlin",
    speciesFrench: "Faucon émerillon",
    speciesScientific: "Falco columbarius",
  },
  MODO: {
    code: "MODO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Mourning Dove",
    speciesDescriptionCMMN: "Mourning Dove",
    speciesFrench: "Tourterelle triste",
    speciesScientific: "Zenaida macroura",
  },
  MOWA: {
    code: "MOWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Mourning Warbler",
    speciesDescriptionCMMN: "Mourning Warbler",
    speciesFrench: "Paruline triste",
    speciesScientific: "Geothlypis philadelphia",
  },
  MYWA: {
    code: "MYWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Yellow-rumped (Myrtle) Warbler",
    speciesDescriptionCMMN: "Myrtle Warbler",
    speciesFrench: "Paruline à croupion jaune",
    speciesScientific: "Setophaga coronata coronata",
  },
  NAWA: {
    code: "NAWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Nashville Warbler",
    speciesDescriptionCMMN: "Nashville Warbler",
    speciesFrench: "Paruline à joues grises",
    speciesScientific: "Leiothlypis ruficapilla",
  },
  NHOW: {
    code: "NHOW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Hawk Owl",
    speciesDescriptionCMMN: "",
    speciesFrench: "Chouette épervière",
    speciesScientific: "Surnia ulula",
  },
  NOCA: {
    code: "NOCA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Cardinal",
    speciesDescriptionCMMN: "Northern Cardinal",
    speciesFrench: "Cardinal rouge",
    speciesScientific: "Cardinalis cardinalis",
  },
  NOGA: {
    code: "NOGA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Gannet",
    speciesDescriptionCMMN: "Northern Gannet",
    speciesFrench: "Fou de Bassan",
    speciesScientific: "Morus bassanus",
  },
  NOGO: {
    code: "NOGO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Goshawk",
    speciesDescriptionCMMN: "Northern Goshawk",
    speciesFrench: "Autour des palombes",
    speciesScientific: "Accipiter gentilis",
  },
  NOHA: {
    code: "NOHA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Harrier",
    speciesDescriptionCMMN: "Northern Harrier",
    speciesFrench: "Busard des marais",
    speciesScientific: "Circus hudsonius",
  },
  NOMO: {
    code: "NOMO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Mockingbird",
    speciesDescriptionCMMN: "Northern Mockingbird",
    speciesFrench: "Moqueur polyglotte",
    speciesScientific: "Mimus polyglottos",
  },
  NOPA: {
    code: "NOPA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Parula",
    speciesDescriptionCMMN: "Northern Parula",
    speciesFrench: "Paruline à collier",
    speciesScientific: "Setophaga americana",
  },
  NOPI: {
    code: "NOPI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Pintail",
    speciesDescriptionCMMN: "Northern Pintail",
    speciesFrench: "Canard pilet",
    speciesScientific: "Anas acuta",
  },
  NOWA: {
    code: "NOWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Waterthrush",
    speciesDescriptionCMMN: "Northern Waterthrush",
    speciesFrench: "Paruline des ruisseaux",
    speciesScientific: "Parkesia noveboracensis",
  },
  NRWS: {
    code: "NRWS",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Rough-winged Swallow",
    speciesDescriptionCMMN: "Northern Rough-winged Swallow",
    speciesFrench: "Hirondelle à ailes hérissées",
    speciesScientific: "Stelgidopteryx serripennis",
  },
  NSHO: {
    code: "NSHO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Shoveler",
    speciesDescriptionCMMN: "Northern Shoveler",
    speciesFrench: "Canard souchet",
    speciesScientific: "Spatula clypeata",
  },
  NSHR: {
    code: "NSHR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Shrike",
    speciesDescriptionCMMN: "Northern Shrike",
    speciesFrench: "Pie-grièche boréale",
    speciesScientific: "Lanius borealis",
  },
  NSWO: {
    code: "NSWO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Northern Saw-whet Owl",
    speciesDescriptionCMMN: "Northern Saw-whet Owl",
    speciesFrench: "Petite Nyctale",
    speciesScientific: "Aegolius acadicus",
  },
  OCWA: {
    code: "OCWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Orange-crowned Warbler",
    speciesDescriptionCMMN: "Orange-crowned Warbler",
    speciesFrench: "Paruline verdâtre",
    speciesScientific: "Leiothlypis celata",
  },
  OROR: {
    code: "OROR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Orchard Oriole",
    speciesDescriptionCMMN: "Orchard Oriole",
    speciesFrench: "Oriole des vergers",
    speciesScientific: "Icterus spurius",
  },
  OSFL: {
    code: "OSFL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Olive-sided Flycatcher",
    speciesDescriptionCMMN: "Olive-sided Flycatcher",
    speciesFrench: "Moucherolle à côtés olive",
    speciesScientific: "Contopus cooperi",
  },
  OSPR: {
    code: "OSPR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Osprey",
    speciesDescriptionCMMN: "Osprey",
    speciesFrench: "Balbuzard pêcheur",
    speciesScientific: "Pandion haliaetus",
  },
  OVEN: {
    code: "OVEN",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Ovenbird",
    speciesDescriptionCMMN: "Ovenbird",
    speciesFrench: "Paruline couronnée",
    speciesScientific: "Seiurus aurocapilla",
  },
  REDH: {
    code: "REDH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Redhead",
    speciesDescriptionCMMN: "Redhead",
    speciesFrench: "Fuligule à tête rouge",
    speciesScientific: "Aythya americana",
  },
  REVI: {
    code: "REVI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Red-eyed Vireo",
    speciesDescriptionCMMN: "Red-eyed Vireo",
    speciesFrench: "Viréo aux yeux rouges",
    speciesScientific: "Vireo olivaceus",
  },
  RLHA: {
    code: "RLHA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Rough-legged Hawk",
    speciesDescriptionCMMN: "Rough-legged Hawk",
    speciesFrench: "Buse pattue",
    speciesScientific: "Buteo lagopus",
  },
  RNDU: {
    code: "RNDU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Ring-necked Duck",
    speciesDescriptionCMMN: "Ring-necked Duck",
    speciesFrench: "Fuligule à collier",
    speciesScientific: "Aythya collaris",
  },
  ROGO: {
    code: "ROGO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Ross's Goose",
    speciesDescriptionCMMN: "Ross's Goose",
    speciesFrench: "Oie de Ross",
    speciesScientific: "Anser rossii",
  },
  ROPI: {
    code: "ROPI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Rock Pigeon",
    speciesDescriptionCMMN: "Rock Pigeon",
    speciesFrench: "Pigeon biset",
    speciesScientific: "Columba livia",
  },
  RSHA: {
    code: "RSHA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Red-shouldered Hawk",
    speciesDescriptionCMMN: "Red-shouldered Hawk",
    speciesFrench: "Buse à épaulettes",
    speciesScientific: "Buteo lineatus",
  },
  RTHA: {
    code: "RTHA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Red-tailed Hawk",
    speciesDescriptionCMMN: "Red-tailed Hawk",
    speciesFrench: "Buse à queue rousse",
    speciesScientific: "Buteo jamaicensis",
  },
  RTHU: {
    code: "RTHU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Ruby-throated Hummingbird",
    speciesDescriptionCMMN: "Ruby-throated Hummingbird",
    speciesFrench: "Colibri à gorge rubis",
    speciesScientific: "Archilochus colubris",
  },
  RUBL: {
    code: "RUBL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Rusty Blackbird",
    speciesDescriptionCMMN: "Rusty Blackbird",
    speciesFrench: "Quiscale rouilleux",
    speciesScientific: "Euphagus carolinus",
  },
  RUGR: {
    code: "RUGR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Ruffed Grouse",
    speciesDescriptionCMMN: "Ruffed Grouse",
    speciesFrench: "Gélinotte huppée",
    speciesScientific: "Bonasa umbellus",
  },
  RWBL: {
    code: "RWBL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Red-winged Blackbird",
    speciesDescriptionCMMN: "Red-winged Blackbird",
    speciesFrench: "Carouge à épaulettes",
    speciesScientific: "Agelaius phoeniceus",
  },
  SACR: {
    code: "SACR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Sandhill Crane",
    speciesDescriptionCMMN: "Sandhill Crane",
    speciesFrench: "Grue du Canada",
    speciesScientific: "Antigone canadensis",
  },
  SAVS: {
    code: "SAVS",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Savannah Sparrow",
    speciesDescriptionCMMN: "Savannah Sparrow",
    speciesFrench: "Bruant des prés",
    speciesScientific: "Passerculus sandwichensis",
  },
  SBDO: {
    code: "SBDO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Short-billed Dowhitcher",
    speciesDescriptionCMMN: "Short-billed Dowhitcher",
    speciesFrench: "Bécassin roux",
    speciesScientific: "Limnodromus griseus",
  },
  SCJU: {
    code: "SCJU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Dark-eyed (Slate-colored) Junco",
    speciesDescriptionCMMN: "Slate-colored Junco",
    speciesFrench: "Junco ardoisé",
    speciesScientific: "Junco hyemalis hyemalis",
  },
  SCTA: {
    code: "SCTA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Scarlet Tanager",
    speciesDescriptionCMMN: "Scarlet Tanager",
    speciesFrench: "Piranga écarlate",
    speciesScientific: "Piranga olivacea",
  },
  PAWA: {
    code: "PAWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Palm Warbler",
    speciesDescriptionCMMN: "Palm Warbler",
    speciesFrench: "Paruline à couronne rousse",
    speciesScientific: "Setophaga palmarum",
  },
  PBGR: {
    code: "PBGR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Pied-billed Grebe",
    speciesDescriptionCMMN: "Pied-billed Grebe",
    speciesFrench: "Grèbe à bec bigarré",
    speciesScientific: "Podilymbus podiceps",
  },
  PEFA: {
    code: "PEFA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Peregrine Falcon",
    speciesDescriptionCMMN: "Peregrine Falcon",
    speciesFrench: "Faucon pèlerin",
    speciesScientific: "Falco peregrinus",
  },
  PHVI: {
    code: "PHVI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Philadelphia Vireo",
    speciesDescriptionCMMN: "Philadelphia Vireo",
    speciesFrench: "Viréo de Philadelphie",
    speciesScientific: "Vireo philadelphicus",
  },
  PIGR: {
    code: "PIGR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Pine Grosbeak",
    speciesDescriptionCMMN: "Pine Grosbeak",
    speciesFrench: "Durbec des sapins",
    speciesScientific: "Pinicola enucleator",
  },
  PISI: {
    code: "PISI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Pine Siskin",
    speciesDescriptionCMMN: "Pine Siskin",
    speciesFrench: "Tarin des pins",
    speciesScientific: "Spinus pinus",
  },
  PIWA: {
    code: "PIWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Pine Warbler",
    speciesDescriptionCMMN: "Pine Warbler",
    speciesFrench: "Paruline des pins",
    speciesScientific: "Setophaga pinus",
  },
  PIWO: {
    code: "PIWO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Pileated Woodpecker",
    speciesDescriptionCMMN: "Pileated Woodpecker",
    speciesFrench: "Grand Pic",
    speciesScientific: "Dryocopus pileatus",
  },
  PUFI: {
    code: "PUFI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Purple Finch",
    speciesDescriptionCMMN: "Purple Finch",
    speciesFrench: "Roselin pourpré",
    speciesScientific: "Haemorhous purpureus",
  },
  PUMA: {
    code: "PUMA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Purple Martin",
    speciesDescriptionCMMN: "Purple Martin",
    speciesFrench: "Hirondelle noire",
    speciesScientific: "Progne subis",
  },
  RBGR: {
    code: "RBGR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Rose-breasted Grosbeak",
    speciesDescriptionCMMN: "Rose-breasted Grosbeak",
    speciesFrench: "Cardinal à poitrine rose",
    speciesScientific: "Pheucticus ludovicianus",
  },
  RBGU: {
    code: "RBGU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Ring-billed Gull",
    speciesDescriptionCMMN: "Ring-billed Gull",
    speciesFrench: "Goéland à bec cerclé",
    speciesScientific: "Larus delawarensis",
  },
  RBME: {
    code: "RBME",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Red-breasted Merganser",
    speciesDescriptionCMMN: "Red-breasted Merganser",
    speciesFrench: "Harle huppé",
    speciesScientific: "Mergus serrator",
  },
  RBNU: {
    code: "RBNU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Red-breasted Nuthatch",
    speciesDescriptionCMMN: "Red-breasted Nuthatch",
    speciesFrench: "Sittelle à poitrine rousse",
    speciesScientific: "Sitta canadensis",
  },
  RBWO: {
    code: "RBWO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Red-bellied Woodpecker",
    speciesDescriptionCMMN: "Red-bellied Woodpecker",
    speciesFrench: "Pic à ventre roux",
    speciesScientific: "Melanerpes carolinus",
  },
  RCKI: {
    code: "RCKI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Ruby-crowned Kinglet",
    speciesDescriptionCMMN: "Ruby-crowned Kinglet",
    speciesFrench: "Roitelet à couronne rubis",
    speciesScientific: "Regulus calendula",
  },
  RECR: {
    code: "RECR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Red Crossbill",
    speciesDescriptionCMMN: "Red Crossbill",
    speciesFrench: "Bec-croisé des sapins",
    speciesScientific: "Loxia curvirostra",
  },
  SEOW: {
    code: "SEOW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Short-eared Owl",
    speciesDescriptionCMMN: "Short-eared Owl",
    speciesFrench: "Hibou des marais",
    speciesScientific: "Asio flammeus",
  },
  SEPL: {
    code: "SEPL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Semipalmated Plover",
    speciesDescriptionCMMN: "Semipalmated Plover",
    speciesFrench: "Pluvier semipalmé",
    speciesScientific: "Charadrius semipalmatus",
  },
  SESA: {
    code: "SESA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Semipalmated Sandpiper",
    speciesDescriptionCMMN: "Semipalmated Sandpiper",
    speciesFrench: "Bécasseau semipalmé",
    speciesScientific: "Calidris pusilla",
  },
  SEWR: {
    code: "SEWR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Sedge Wren",
    speciesDescriptionCMMN: "Sedge Wren",
    speciesFrench: "Troglodyte à bec court",
    speciesScientific: "Cistothorus platensis",
  },
  SNBU: {
    code: "SNBU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Snow Bunting",
    speciesDescriptionCMMN: "Snow Bunting",
    speciesFrench: "Plectrophane des neiges",
    speciesScientific: "Plectrophenax nivalis",
  },
  SNGO: {
    code: "SNGO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Snow Goose",
    speciesDescriptionCMMN: "Snow Goose",
    speciesFrench: "Oie des neiges",
    speciesScientific: "Anser caerulescens",
  },
  SNOW: {
    code: "SNOW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Snowy Owl",
    speciesDescriptionCMMN: "",
    speciesFrench: "Harfang des neiges",
    speciesScientific: "Bubo scandiacus",
  },
  SORA: {
    code: "SORA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Sora",
    speciesDescriptionCMMN: "Sora",
    speciesFrench: "Marouette de Caroline",
    speciesScientific: "Porzana carolina",
  },
  SOSA: {
    code: "SOSA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Solitary Sandpiper",
    speciesDescriptionCMMN: "Solitary Sandpiper",
    speciesFrench: "Chevalier solitaire",
    speciesScientific: "Tringa solitaria",
  },
  SOSP: {
    code: "SOSP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Song Sparrow",
    speciesDescriptionCMMN: "Song Sparrow",
    speciesFrench: "Bruant chanteur",
    speciesScientific: "Melospiza melodia",
  },
  SPSA: {
    code: "SPSA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Spotted Sandpiper",
    speciesDescriptionCMMN: "Spotted Sandpiper",
    speciesFrench: "Chevalier grivelé",
    speciesScientific: "Actitis macularius",
  },
  SSHA: {
    code: "SSHA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Sharp-shinned Hawk",
    speciesDescriptionCMMN: "Sharp-shinned Hawk",
    speciesFrench: "Épervier brun",
    speciesScientific: "Accipiter striatus",
  },
  SWSP: {
    code: "SWSP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Swamp Sparrow",
    speciesDescriptionCMMN: "Swamp Sparrow",
    speciesFrench: "Bruant des marais",
    speciesScientific: "Melospiza georgiana",
  },
  SWTH: {
    code: "SWTH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Swainson's Thrush",
    speciesDescriptionCMMN: "Swainson's Thrush",
    speciesFrench: "Grive à dos olive",
    speciesScientific: "Catharus ustulatus",
  },
  TEWA: {
    code: "TEWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Tennessee Warbler",
    speciesDescriptionCMMN: "Tennessee Warbler",
    speciesFrench: "Paruline obscure",
    speciesScientific: "Leiothlypis peregrina",
  },
  TOSO: {
    code: "TOSO",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Townsend's Solitaire",
    speciesDescriptionCMMN: "Townsend's Solitaire",
    speciesFrench: "Solitaire de Townsend",
    speciesScientific: "Myadestes townsendi",
  },
  TRES: {
    code: "TRES",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Tree Swallow",
    speciesDescriptionCMMN: "Tree Swallow",
    speciesFrench: "Hirondelle bicolore",
    speciesScientific: "Tachycineta bicolor",
  },
  TRFL: {
    code: "TRFL",
    pseudoSpeciesType: "Superspecies",
    speciesDescriptionMBO: "Traill's Flycatcher",
    speciesDescriptionCMMN: "Traill's Flycatcher (Willow or Alder)",
    speciesFrench: "Moucherolle des saules ou M. des aulnes",
    speciesScientific: "Empidonax traillii or alnorum",
  },
  TUSW: {
    code: "TUSW",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Tundra Swan",
    speciesDescriptionCMMN: "Tundra Swan",
    speciesFrench: "Cygne siffleur",
    speciesScientific: "Cygnus columbianus",
  },
  TUTI: {
    code: "TUTI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Tufted Titmouse",
    speciesDescriptionCMMN: "Tufted Titmouse",
    speciesFrench: "Mésange bicolore",
    speciesScientific: "Baeolophus bicolor",
  },
  TUVU: {
    code: "TUVU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Turkey Vulture",
    speciesDescriptionCMMN: "Turkey Vulture",
    speciesFrench: "Urubu à tête rouge",
    speciesScientific: "Cathartes aura",
  },
  USCA: {
    code: "USCA",
    pseudoSpeciesType: "Superspecies",
    speciesDescriptionMBO: "Unidentified Scaup sp.",
    speciesDescriptionCMMN: "Unidentified Scaup",
    speciesFrench: "Aythya sp.",
    speciesScientific: "Aythya sp.",
  },
  VEER: {
    code: "VEER",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Veery",
    speciesDescriptionCMMN: "Veery",
    speciesFrench: "Grive fauve",
    speciesScientific: "Catharus fuscescens",
  },
  VESP: {
    code: "VESP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Vesper Sparrow",
    speciesDescriptionCMMN: "Vesper Sparrow",
    speciesFrench: "Bruant vespéral",
    speciesScientific: "Pooecetes gramineus",
  },
  VIRA: {
    code: "VIRA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Virginia Rail",
    speciesDescriptionCMMN: "Virginia Rail",
    speciesFrench: "Râle de Virginie",
    speciesScientific: "Rallus limicola",
  },
  WAVI: {
    code: "WAVI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Warbling Vireo",
    speciesDescriptionCMMN: "Warbling Vireo",
    speciesFrench: "Viréo mélodieux",
    speciesScientific: "Vireo gilvus",
  },
  WBNU: {
    code: "WBNU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "White-breasted Nuthatch",
    speciesDescriptionCMMN: "White-breasted Nuthatch",
    speciesFrench: "Sittelle à poitrine blanche",
    speciesScientific: "Sitta carolinensis",
  },
  WEVI: {
    code: "WEVI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "White-eyed Vireo",
    speciesDescriptionCMMN: "White-eyed Vireo",
    speciesFrench: "Viréo aux yeux blancs",
    speciesScientific: "Vireo griseus",
  },
  WEWA: {
    code: "WEWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Worm-eating Warbler",
    speciesDescriptionCMMN: "Worm-eating Warbler",
    speciesFrench: "Paruline vermivore",
    speciesScientific: "Helmitheros vermivorum",
  },
  WIFL: {
    code: "WIFL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Willow Flycatcher",
    speciesDescriptionCMMN: "Willow Flycatcher",
    speciesFrench: "Moucherolle des saules",
    speciesScientific: "Empidonax traillii",
  },
  WISN: {
    code: "WISN",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Wilson's Snipe",
    speciesDescriptionCMMN: "Wilson's Snipe",
    speciesFrench: "Bécassine de Wilson",
    speciesScientific: "Gallinago delicata",
  },
  WITU: {
    code: "WITU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Wild Turkey",
    speciesDescriptionCMMN: "Wild Turkey",
    speciesFrench: "Dindon sauvage",
    speciesScientific: "Meleagris gallopavo",
  },
  WIWA: {
    code: "WIWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Wilson's Warbler",
    speciesDescriptionCMMN: "Wilson's Warbler",
    speciesFrench: "Paruline à calotte noire",
    speciesScientific: "Cardellina pusilla",
  },
  WIWR: {
    code: "WIWR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Winter Wren",
    speciesDescriptionCMMN: "Winter Wren",
    speciesFrench: "Troglodyte des forêts",
    speciesScientific: "Troglodytes hiemalis",
  },
  WODU: {
    code: "WODU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Wood Duck",
    speciesDescriptionCMMN: "Wood Duck",
    speciesFrench: "Canard branchu",
    speciesScientific: "Aix sponsa",
  },
  WOTH: {
    code: "WOTH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Wood Thrush",
    speciesDescriptionCMMN: "Wood Thrush",
    speciesFrench: "Grive des bois",
    speciesScientific: "Hylocichla mustelina",
  },
  WPWA: {
    code: "WPWA",
    pseudoSpeciesType: "Subspecies",
    speciesDescriptionMBO: "Western Palm Warbler",
    speciesDescriptionCMMN: "Western Palm Warbler",
    speciesFrench: "Paruline à couronne rousse (forme de l'Ouest)",
    speciesScientific: "Setophaga palmarum palmarum",
  },
  WTSP: {
    code: "WTSP",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "White-throated Sparrow",
    speciesDescriptionCMMN: "White-throated Sparrow",
    speciesFrench: "Bruant à gorge blanche",
    speciesScientific: "Zonotrichia albicollis",
  },
  WWCR: {
    code: "WWCR",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "White-winged Crossbill",
    speciesDescriptionCMMN: "White-winged Crossbill",
    speciesFrench: "Bec-croisé bifascié",
    speciesScientific: "Loxia leucoptera",
  },
  WWSC: {
    code: "WWSC",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "White-winged Scoter",
    speciesDescriptionCMMN: "White-winged Scoter",
    speciesFrench: "Macreuse brune",
    speciesScientific: "Melanitta deglandi",
  },
  YBCU: {
    code: "YBCU",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Yellow-billed Cuckoo",
    speciesDescriptionCMMN: "Yellow-billed Cuckoo",
    speciesFrench: "Coulicou à bec jaune",
    speciesScientific: "Coccyzus americanus",
  },
  YBFL: {
    code: "YBFL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Yellow-bellied Flycatcher",
    speciesDescriptionCMMN: "Yellow-bellied Flycatcher",
    speciesFrench: "Moucherolle à ventre jaune",
    speciesScientific: "Empidonax flaviventris",
  },
  YBSA: {
    code: "YBSA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Yellow-bellied Sapsucker",
    speciesDescriptionCMMN: "Yellow-bellied Sapsucker",
    speciesFrench: "Pic maculé",
    speciesScientific: "Sphyrapicus varius",
  },
  YEWA: {
    code: "YEWA",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Yellow Warbler",
    speciesDescriptionCMMN: "Yellow Warbler",
    speciesFrench: "Paruline jaune",
    speciesScientific: "Setophaga petechia",
  },
  YPWA: {
    code: "YPWA",
    pseudoSpeciesType: "Subspecies",
    speciesDescriptionMBO: "Yellow Palm Warbler",
    speciesDescriptionCMMN: "Yellow Palm Warbler",
    speciesFrench: "Paruline à couronne rousse (forme de l'Est)",
    speciesScientific: "Setophaga palmarum hypochrysea",
  },
  YSFL: {
    code: "YSFL",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Yellow-shafted Flicker",
    speciesDescriptionCMMN: "Yellow-shafted Flicker",
    speciesFrench: "Pic flamboyant",
    speciesScientific: "Colaptes auratus auratus",
  },
  YTVI: {
    code: "YTVI",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Yellow-throated Vireo",
    speciesDescriptionCMMN: "Yellow-throated Vireo",
    speciesFrench: "Viréo à gorge jaune",
    speciesScientific: "Vireo flavifrons",
  },
  HUWH: {
    code: "HUWH",
    pseudoSpeciesType: "Species",
    speciesDescriptionMBO: "Hudsonian Whimbrel",
    speciesDescriptionCMMN: "Hudsonian Whimbrel",
    speciesFrench: "Courlis hudsonien",
    speciesScientific: "Numenius hudsonicus",
  }
};
