export const HeadersToCaptureMap = {
    
  BandPrefix: BandPrefix,
  BandSuffix: BandSuffix,
  Species: Species,
  WingChord: WingChord,
  Age: Age,
  HowAged: HowAged,
  Sex: Sex,
  HowSexed: HowSexed,
  Fat: Fat,
  Weight: Weight,
  CaptureDate: CaptureDate,
  Bander: Bander,
  Scribe: Scribe,
  Net: Net,
  NotesForMBO: NotesForMBO,
  Location: Location,
  BirdStatus: BirdStatus,
  PresentCondition: PresentCondition,
  HowObtainedCode: HowObtainedCode,
  Program: Program,
  D18: D18,
  D20: D20,
  D22: D22,
};
